name: Deploy to Test VM

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: echo "Running on self-hosted runner"

    steps:
    # 1. 저장소 코드 가져오기
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Java 환경 세팅
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 2-1. gradlew 실행 권한 부여
    - name: Make gradlew executable
      run: chmod +x gradlew

    # 3. Gradle 빌드
    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # 4. VM에 업로드
    - name: Copy build files to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        source: "build/libs/*.jar"
        target: "/home/webmsg/web/testSbb/"

    # 5. VM에서 애플리케이션 실행
    - name: Run application on VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        port: ${{ secrets.VM_PORT }}
        script: |
          cd /home/webmsg/web/testSbb
          # 이전 실행 중인 프로세스 종료
          pkill -f 'java -jar sbb-0.0.1-SNAPSHOT.jar' || true
          # 새로운 애플리케이션 실행 (백그라운드)
          nohup java -jar sbb-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
