name: Deploy to Test VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # 1. 저장소 코드 가져오기
      - uses: actions/checkout@v4

      # 2. Java 환경 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. gradlew 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. JAR 파일을 VM으로 복사 (scp 사용)
      - name: Copy build files to VM via scp
        run: |
          scp -P ${{ secrets.VM_PORT }} \
            build/libs/*.jar \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/webmsg/web/testSbb/

      # 6. VM에서 애플리케이션 실행 (ssh 사용)
      - name: Run application on VM via ssh
        run: |
          ssh -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/webmsg/web/testSbb
            pkill -f 'java -jar sbb-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar sbb-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
