name: Deploy to Test VM (new-branch)

on:
  push:
    branches:
      - new-branch   # new-branch에 push될 때 실행

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 60  # 최대 60분까지 허용
    steps:
      # 1. 저장소 코드 가져오기
      - uses: actions/checkout@v4

      # 2. Java 환경 세팅
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. gradlew 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. JAR 파일을 VM으로 안정적으로 복사 (rsync 사용)
      - name: Copy build files to VM via rsync
        run: |
          rsync -avz -e "ssh -p ${{ secrets.VM_PORT }}" \
            build/libs/sbb-0.0.1-SNAPSHOT.jar \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/webmsg/web/testSbb/

      # 6. VM에서 애플리케이션 실행 (ssh 사용)
      - name: Run application on VM via ssh
        run: |
          ssh -p ${{ secrets.VM_PORT }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            cd /home/webmsg/web/testSbb
            # 이전 실행 중인 프로세스 종료
            pkill -f 'java -jar sbb-0.0.1-SNAPSHOT.jar' || true
            # 새로운 애플리케이션 실행 (백그라운드)
            nohup java -jar sbb-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
          EOF
